# Generated by Django 3.1.5 on 2021-01-16 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('light', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lightsample',
            old_name='type',
            new_name='light_type',
        ),
    ]
